apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: new-app
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-port
      protocol: TCP
      port: 9002
      targetPort: 1180
