apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
spec:
  containers:
  - name: multitool-container
    image: wbitt/network-multitool:latest
    ports:
    - containerPort: 8080
    command: ["/bin/sh", "-c"]
    args:
    - "sleep 999999"
